# Generated by Django 4.2 on 2024-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkadaKnowledgeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'AkadaKnowledgeBank',
                'verbose_name_plural': 'AkadaKnowledgeBank',
            },
        ),
    ]
