# Generated by Django 4.2 on 2024-02-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akadaknowledgebank',
            name='file_path',
        ),
    ]
