# Generated by Django 4.2 on 2025-04-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_subscriptionplan_akada_price_and_more'),
        ('akada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedStudyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.quest')),
            ],
            options={
                'verbose_name': 'GeneratedStudyMaterials',
                'verbose_name_plural': 'GeneratedStudyMaterials',
            },
        ),
    ]
