# Generated by Django 4.2 on 2025-04-19 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akada', '0002_generatedstudymaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedstudymaterials',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked_study_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
