# Generated by Django 4.2 on 2025-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akada', '0003_generatedstudymaterials_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedstudymaterials',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
