# Generated by Django 4.2 on 2025-04-19 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akada', '0004_alter_generatedstudymaterials_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedstudymaterials',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_study_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
