# Generated by Django 4.2 on 2025-08-07 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akada', '0005_alter_generatedstudymaterials_bookmarked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerativeAIContentReport',
            fields=[
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('reason', models.CharField(help_text='User-provided reason for the report.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken')], default='pending', max_length=50)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generative AI Content Report',
                'verbose_name_plural': 'Generative AI Content Reports',
            },
        ),
    ]
