# Generated by Django 4.2 on 2025-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akada', '0006_generativeaicontentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generativeaicontentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
