# Generated by Django 4.2 on 2024-01-12 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeredby',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.question'),
        ),
        migrations.AddField(
            model_name='answeredby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
