# Generated by Django 4.2 on 2025-03-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='bookmarked',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='bookmarked',
        ),
    ]
