# Generated by Django 4.2 on 2025-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_library_bookmarked_quest_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='akada_price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='bookee_price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='quest_price',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
