# Generated by Django 4.2 on 2024-01-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_answeredby_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredby',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to='admin_app.question'),
        ),
    ]
