# Generated by Django 4.2 on 2024-01-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_answeredby_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
