# Generated by Django 4.2 on 2025-04-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0001_initial'),
        ('admin_app', '0004_remove_subscriptionplan_akada_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_quests', to='learningpost_professional.professionalorganization'),
        ),
    ]
