# Generated by Django 4.2 on 2024-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_quest_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='quest_covers/')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
    ]
