# Generated by Django 4.2 on 2024-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='cover',
            field=models.ImageField(upload_to='book_covers/'),
        ),
    ]
