# Generated by Django 4.2 on 2025-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_leaderboard_date_leaderboard_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
