# Generated by Django 4.2 on 2024-01-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0007_alter_library_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_quests', to='admin_app.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_books', to='admin_app.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
