# Generated by Django 4.2 on 2025-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_leaderboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
