# Generated by Django 4.2 on 2024-01-30 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0008_library_bookmarked_questrating_libraryrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quest',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
