# Generated by Django 4.2 on 2025-06-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0009_question_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('question_report', 'question_report'), ('help_desk', 'help_desk'), ('unsatisfied_user', 'unsatisfied_user')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
