# Generated by Django 4.2 on 2024-02-01 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_library_bookmarked_alter_quest_bookmarked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chapter_file', models.FileField(upload_to='chapters/', validators=[django.core.validators.FileExtensionValidator(['epub'])])),
            ],
        ),
    ]
