# Generated by Django 4.2 on 2025-07-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_userfeedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN')], default='NGN', max_length=5, null=True),
        ),
    ]
