# Generated by Django 4.2 on 2025-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_subscriptionplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP')], default='NGN', max_length=5, null=True),
        ),
    ]
