# Generated by Django 4.2 on 2024-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_chapter_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='about_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
