# Generated by Django 4.2 on 2024-02-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_library_about_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
