# Generated by Django 4.2 on 2025-08-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_subscriptionplan_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'UserFeedback', 'verbose_name_plural': 'UserFeedback'},
        ),
    ]
