# Generated by Django 4.2 on 2025-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_userfeedback_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
