# Generated by Django 4.2 on 2024-02-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='date',
        ),
    ]
