# Generated by Django 4.2 on 2024-02-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('question_report', 'question_report'), ('help_desk', 'help_desk')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.question'),
        ),
    ]
