# Generated by Django 4.2 on 2024-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_userfeedback_feedback_type_userfeedback_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
