# Generated by Django 4.2 on 2024-02-23 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0018_library_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answered', models.IntegerField()),
                ('correctly_answered', models.IntegerField()),
                ('wrongly_answered', models.IntegerField()),
                ('date', models.DateField()),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
