# Generated by Django 4.2 on 2024-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_mperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mperformance',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
