# Generated by Django 4.2 on 2024-02-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_mperformance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
