# Generated by Django 4.2 on 2024-02-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_quest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
