# Generated by Django 4.2 on 2024-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_quest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.TextField(default=''),
        ),
    ]
