# Generated by Django 4.2 on 2024-04-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
