# Generated by Django 4.2 on 2024-04-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_quest_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='quest_type',
        ),
    ]
