# Generated by Django 4.2 on 2024-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_remove_quest_quest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
