# Generated by Django 4.2 on 2024-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_library_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('quest_price', models.IntegerField()),
                ('bookee_price', models.IntegerField()),
                ('akada_price', models.IntegerField()),
            ],
        ),
    ]
