# Generated by Django 4.2 on 2025-04-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_usersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAccounts',
        ),
    ]
