# Generated by Django 4.2 on 2024-01-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_user_date_of_birth_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referal_code',
        ),
        migrations.CreateModel(
            name='BetaReferal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='website.userprofile')),
            ],
        ),
    ]
