# Generated by Django 4.2 on 2024-01-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_userprofile_referal_code_betareferal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betareferal',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='website.userprofile'),
        ),
    ]
