# Generated by Django 4.2 on 2025-05-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='grades',
            field=models.JSONField(default={'grades': []}),
        ),
    ]
