# Generated by Django 4.2 on 2024-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_subaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betareferal',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
