# Generated by Django 4.2 on 2025-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_usersubscription_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='grades',
            field=models.TextField(blank=True, default=''),
        ),
    ]
