# Generated by Django 4.2 on 2025-08-29 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_usersubscription_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(blank=True, help_text="Upload a clear image of the user's face for proctoring.", null=True, upload_to='reference_faces/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProUserProfile',
                'verbose_name_plural': 'ProUserProfiles',
            },
        ),
    ]
