# Generated by Django 4.2 on 2024-04-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('support_quest', models.BooleanField(default=True)),
                ('support_bookee', models.BooleanField(default=True)),
                ('support_akada', models.BooleanField(default=True)),
                ('supported_grades', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='website.userprofile')),
            ],
        ),
    ]
