# Generated by Django 4.2 on 2024-04-12 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('code', models.SlugField(unique=True)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
