# Generated by Django 4.2 on 2024-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_subscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='currency',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
