# Generated by Django 4.2 on 2024-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_subscriptionlog_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
