# Generated by Django 4.2 on 2024-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_subscriptionlog_is_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlog',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
