# Generated by Django 4.2 on 2024-05-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_subscriptionlog_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(choices=[('The African Church Model College', 'The African Church Model College'), ('Other', 'Other')], default='Other', max_length=200, null=True),
        ),
    ]
