# Generated by Django 4.2 on 2025-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_userprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(choices=[('The African Church Model College', 'The African Church Model College'), ('Other', 'Other')], default=('Other', 'Other'), max_length=200, null=True),
        ),
    ]
