# Generated by Django 4.2 on 2025-03-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_userprofile_user_user_country_user_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='profile',
        ),
        migrations.DeleteModel(
            name='SubscriptionLog',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
