# Generated by Django 4.2 on 2025-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalorganization',
            name='organization_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
