# Generated by Django 4.2 on 2025-06-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0004_alter_professionalorganization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalorganization',
            name='organization_logo',
            field=models.ImageField(null=True, upload_to='organization_logos/'),
        ),
    ]
