# Generated by Django 4.2 on 2025-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0006_test_pass_mark_testattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pass_mark',
            field=models.FloatField(default=75.0),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
