# Generated by Django 4.2 on 2025-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0007_alter_test_pass_mark_alter_testattempt_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='is_voided',
            field=models.BooleanField(default=True),
        ),
    ]
