# Generated by Django 4.2 on 2025-09-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0008_alter_testattempt_is_voided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
