# Generated by Django 5.2 on 2025-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0009_alter_testattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
