# Generated by Django 5.2 on 2025-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0010_testattempt_is_attempted_alter_testattempt_is_voided'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='exam',
            new_name='test',
        ),
    ]
