# Generated by Django 4.2 on 2025-09-14 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learningpost_professional', '0011_rename_exam_testattempt_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
