# Generated by Django 4.2 on 2024-03-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengescore',
            old_name='score',
            new_name='score_1',
        ),
        migrations.RemoveField(
            model_name='challengeroom',
            name='no_of_rounds',
        ),
        migrations.AddField(
            model_name='challengeroom',
            name='room_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='challengescore',
            name='score_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengescore',
            name='score_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengescore',
            name='score_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengescore',
            name='score_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengeroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='challengeroom',
            name='room_name',
            field=models.CharField(max_length=20),
        ),
    ]
