# Generated by Django 4.2 on 2025-05-09 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0008_alter_leaderboard_date'),
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('questions', models.IntegerField(default=20)),
                ('time', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('room_slug', models.SlugField(null=True, unique=True)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='challenge_app.arenaroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='challengescore',
            name='room',
        ),
        migrations.RemoveField(
            model_name='challengescore',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChallengeRoom',
        ),
        migrations.DeleteModel(
            name='ChallengeScore',
        ),
    ]
