# Generated by Django 4.2 on 2025-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0002_arenaroom_participants_remove_challengescore_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaroom',
            name='questions',
            field=models.IntegerField(default=10),
        ),
    ]
