# Generated by Django 4.2 on 2024-03-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_quest_category'),
        ('challenge_app', '0002_rename_score_challengescore_score_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeroom',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.quest'),
        ),
    ]
