# Generated by Django 4.2 on 2025-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0003_alter_arenaroom_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaroom',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
